# Generated by Django 4.0.5 on 2022-06-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_x_hotel_y_hotel_z_hotel_remove_address_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XYZ_Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Occupant_Name', models.CharField(max_length=90)),
                ('Occupant_Email', models.EmailField(max_length=254)),
                ('Occupant_Occupation', models.CharField(max_length=90)),
                ('Room_number', models.IntegerField()),
                ('Amount_paid', models.CharField(max_length=70)),
                ('Number_of_night', models.IntegerField()),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='X_Hotel',
        ),
        migrations.DeleteModel(
            name='Y_Hotel',
        ),
        migrations.DeleteModel(
            name='Z_Hotel',
        ),
    ]
